// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '7777777777',
    appId: 'jiu889999999',
    messagingSenderId: '937456704579',
    projectId: 'bookstore-dad80',
    authDomain: 'bookstore-dad80.firebaseapp.com',
    storageBucket: 'bookstore-dad80.firebasestorage.app',
    measurementId: 'G-DDYYZ135JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGkCtBf1ivJbK3i16Rzxo03GWqcWOhyXM',
    appId: '1:937456704579:android:da8689ed6f00ec7e8c08f6',
    messagingSenderId: '937456704579',
    projectId: 'bookstore-dad80',
    storageBucket: 'bookstore-dad80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgfDqIvMTAKqoT3YEAzxV0e2gg42NrD1Y',
    appId: '1:937456704579:ios:522bc750f8caf5bd8c08f6',
    messagingSenderId: '937456704579',
    projectId: 'bookstore-dad80',
    storageBucket: 'bookstore-dad80.firebasestorage.app',
    iosBundleId: 'com.example.readify',
  );
}
